obj-$(CONFIG_ARCH_CV183X)	+= clk-cv1835.o
obj-$(CONFIG_ARCH_CV952X)	+= clk-cv1835.o
obj-$(CONFIG_ARCH_CV182X)	+= clk-cv182x.o
obj-$(CONFIG_SOC_SOPHGO_SG2000)		+= clk-cv181x.o
obj-$(CONFIG_ARCH_CV180X)		+= clk-cv180x.o
